<a href="https://colab.research.google.com/github/hari-hashing/Tensorflow_Learning/blob/main/IMAGE_CLASSIFIER_USING_TENSORFLOW_AND_MNIST_DATASET.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **IMAGE CLASSIFIER USING TENSORFLOW AND MNIST DATASET**

In [2]:
import tensorflow as tf
print("Tensorflow version : ",tf.__version__)

Tensorflow version :  2.15.0


In [3]:
# Loading Dataset :

mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [7]:
#  The pixel values of the images range from 0 through 255.
# Scale these values to a range of 0 to 1 by dividing the values by 255.0.
#  This also converts the sample data from integers to floating-point numbers
x_train , x_test = x_train/255.0 , x_test/255.0


In [8]:
x_test

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [11]:
# BUilding a model

# Sequential is useful for stacking layers where each layer has one input tensor and one output tensor.
# Layers are functions with a known mathematical structure that can be reused and have trainable variables.
# Most TensorFlow models are composed of layers. This model uses the Flatten, Dense, and Dropout layers.

# For each example, the model returns a vector of logits or log-odds scores, one for each class.

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Dense(10)
])

In [17]:
# x_train.shape
x_train[:1]

array([[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.0000000

In [18]:
# Note: It is possible to bake the tf.nn.softmax function into the activation function for the last layer of the network.
# While this can make the model output more directly interpretable,
#  this approach is discouraged as it's impossible to provide an exact and
# numerically stable loss calculation for all models when using a softmax output

# untrained model to get some predictions
predictions= model(x_train[:1]).numpy()
predictions

array([[ 0.00112421, -0.00115872,  0.001272  , -0.00246904,  0.00027293,
        -0.00233139, -0.00159028, -0.0003244 , -0.00252184, -0.00081665]],
      dtype=float32)

In [19]:
# The loss function takes a vector of ground truth values and a vector of logits and returns a scalar loss for each example.
#  This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.

# This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to
# -tf.math.log(1/10) ~= 2.3.

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [20]:
loss_fn(y_train[:1],predictions).numpy()

2.3040633

In [21]:
# /Configuration of the model
# before we do it we have to set the
# optimizer to adam and loss funtion to loss_fn defined earlier and a metric to be
# evaluated for the model by setting the metrics parameter to accuracy

model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [24]:
model.fit(x_train,y_train,epochs=5,verbose=1)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3795 - accuracy: 0.8906
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3564 - accuracy: 0.8973
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3407 - accuracy: 0.9017
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3259 - accuracy: 0.9055
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3118 - accuracy: 0.9093


In [25]:
model.evaluate(x_test,y_test,verbose=1)

313/313 [==============================] - 1s 2ms/step - loss: 0.2442 - accuracy: 0.9287


[0.2441677749156952, 0.9286999702453613]

In [27]:
#  to return a probability, you can wrap the trained model, and attach the softmax to it:

prob_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [29]:
prob_model(x_test[:1])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[8.4865191e-05, 6.4704636e-08, 2.5347402e-04, 1.3443725e-03,
        9.8719255e-08, 3.0790146e-05, 7.8755924e-10, 9.9680018e-01,
        7.1984773e-06, 1.4789219e-03]], dtype=float32)>